name: Demo Reminder Automation

on:
  schedule:
    - cron: '*/3 * * * *' # Every 3 minutes for testing purposes
    # - cron: "0 9 * * 1,4" # Monday and Thursday at 09:00 UTC
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Bot Script
        run: node src/index.js
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}