name: Demo Reminder Automation

on:
  schedule:
    - cron: '0 9 * * 2,3,4' 
  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Bot Script
        run: node src/index.js
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          # SLACK_BOT_ITP_TOKEN: ${{ secrets.SLACK_BOT_ITP_TOKEN }}
          # SLACK_ITP_CHANNEL_ID: ${{ secrets.SLACK_ITP_CHANNEL_ID }}
          # SLACK_BOT_ITD_TOKEN: ${{ secrets.SLACK_BOT_ITD_TOKEN }}
          # SLACK_ITD_CHANNEL_ID: ${{ secrets.SLACK_ITD_CHANNEL_ID }}
          # SLACK_BOT_CYF_TOKEN: ${{ secrets.SLACK_BOT_CYF_TOKEN }}
          # SLACK_CYF_CHANNEL_ID: ${{ secrets.SLACK_CYF_CHANNEL_ID }}